### ISSUE TITLE
Inconsistent material between custom  and default map

### ISSUE THREAD

**Issue by t0stiman** [derail-valley-modding/custom-car-loader#152]
**Describe the bug**
While trying to create a glass material I noticed that the custom traincar looked different on the default map vs custom maps. On the default the material is reflective, as intended, but on custom maps its just black.  
I'm not sure whether is a bug in CCL or Mapify.

**To Reproduce**
1. Open the attached Unity project, export the custom car
2. Open DV, start a custom map
3. Spawn the custom car
4. Behold

**Screenshots**
![afbeelding](https://github.com/derail-valley-modding/custom-car-loader/assets/18124323/c25ade26-c845-4d21-b05f-194668fd88c5)
![afbeelding](https://github.com/derail-valley-modding/custom-car-loader/assets/18124323/10ac11d1-9016-4e0f-8995-e11f848b2c40)

**Additional context**
Mapify version: newest commit @ https://github.com/t0stiman/dv-mapify (latest release probably results in the same issue)
CCL version: 2.0.3

Unity project:  
[aaaa.zip](https://github.com/derail-valley-modding/custom-car-loader/files/13064159/aaaa.zip)

**Comment by katycat5e** [comment]
This is likely due to missing environment map/skybox in custom maps, the reflection texture belongs to the scene rather than a property of the individual materials. Unfortunately I'm not sure what would need changed in mapify to correct this.
