### ISSUE TITLE
Port Configuration & Linking

### ISSUE THREAD

**Issue by katycat5e** [derail-valley-modding/custom-car-loader#173]
- [x] Port ID & Fuse ID annotations
- [x] Port editor script, gather list of valid port IDs to show as dropdown?
- [x] Port definitions for sim components
- [x] Sim Connections ~~script/editor~~ (to be generated at import time)
- [x] Logic for linking up real ports at import time (handled by sim connections)

**Comment by lassombra** [comment]
Note - port id and fuse id _filter_ annotation is done in #172, so it's generation annotations that need added.

SimConnections specifically we don't want to do in Unity I think, but rather detect components that create ports and add them to some kind of internal list to make available in port selection - but then we could still save the whole port id - that way we don't have to do any special magic to link up ports at import time - they should just work.  The entire design of the port system is you can put a port id in and as long as you get it right it is attached automatically at spawn.

**Comment by katycat5e** [comment]
Ah I see, I had a misconception about how the annotations were used. So it's the PortDefinition and PortReferenceDefinition that we need the replacement logic for.
