### ISSUE TITLE
Custom Locomotive Manuals

### ISSUE THREAD

**Issue by katycat5e** [derail-valley-modding/custom-car-loader#64]
In-game booklets for custom engines

- [ ] Loading page textures
- [ ] PageTextureData creation - investigate existing manual setup
- [ ] Method for spawning manuals in-game

**Comment by WhistleWiz** [comment]
So considering how manuals no longer exist, and instead we have the catalog (covered already in #249), what should be done about this?

**Comment by katycat5e** [comment]
Closed by #249
